[apps]
port = 8080

[database]
user = "postgres"
password = "postgres"
name = "user_database"
host = "localhost"
port = "5432"
url = "postgresql://postgres:postgres@localhost:5432/user_database"

[redis]
host = "localhost:6379"

[logger]
log = "info"