[package]
name = "posts_consumer"
version = "0.1.0"
edition = "2021"


[dependencies]
rdkafka = "0.37"
futures = "0.3"
tokio = { version = "1", features = ["full"] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
