[apps]
address = "[::1]:50501"

[database]
user = "postgres"
password = "postgres"
name = "user_database"
host = "localhost"
port = "5432"
url = "postgresql://postgres:postgres@localhost:5432/user_database"
min_pool_connection = 10
max_pool_connection = 100
[redis]
host = "localhost:6379"
min_pool_connection = 10
max_pool_connection = 100

[logger]
log = "info"